name: inventario_app
description: "Inventario F치cil - App m칩vil Flutter para gesti칩n de inventario de micro y peque침os negocios"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Database
  drift: ^2.20.3
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Backend and Sync
  supabase_flutter: ^2.5.6
  
  # Routing
  go_router: ^14.2.7
  
  # Image handling
  image_picker: ^1.1.2
  
  # Barcode scanning (for Phase 2)
  mobile_scanner: ^5.2.3
  
  # PDF and CSV export (for Phase 2)
  pdf: ^3.11.1
  printing: ^5.13.2
  csv: ^6.0.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation for Drift
  drift_dev: ^2.20.1
  build_runner: ^2.4.13

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
